# Site settings
title: arashi
name: arashi # your name
# email: N/A # your email address
description: >
    おほそらを　とりかえすとも　きかなくに　ほしかとみゆる　あきのきくかな
baseurl: "" # the subpath of your site, e.g. /blog
url: "arashi35.github.io" # the base hostname & protocol for your site
github_username: arashi35 # your Github username
disqus_username: # your disqus username

google-analytics: # add it if you have one


# Build settings
permalink: none
markdown: kramdown

# default settings, currently configured for posts:
defaults:
  -
    scope:
      path: '_posts'
    values:
        layout: 'post'
